---
- name: "LAMP-Wordpress"
  hosts: amazon
  become: true
  vars_files:
    - variables.tmp

  tasks:
    

    - include_tasks: apache-php.yml
    - include_tasks: maria-db.yml
    - include_tasks: wordpress.yml


    - name: "Post-Installation - CleanUp"
      file:
        path: "{{ item }}"
        state: absent
      with_items:
          - "/tmp/wordpress.tar.gz"
          - "/tmp/wordpress"


  handlers:
    - name: "httpd_restart"
      service:
        name: httpd
        state: restarted
        enabled: true
