---
- name: "LAMP-Wordpress"
  hosts: amazon
  become: true
  vars_files:
    - variables.var

  tasks:
    

    - include_tasks: apache-phpinstallation.yml
    - include_tasks: mariadb-installation.yml
    - include_tasks: wordpress-configuration.yml


    - name: "Post-Installation - CleanUp"
      file:
        path: "{{ item }}"
        state: absent
      with_items:
          - "/tmp/wordpress.tar.gz"
          - "/tmp/wordpress"


  handlers:
    - name: "httpd_restart"
      service:
        name: httpd
        state: restarted
        enabled: true
